### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by likask** [deprint/build-tools-cpp#19]
[Enter steps to reproduce below:]

1. Set setting Key bindings
2. Make command for Ctr-L Ctr-O

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [build-tools-cpp](https://github.com/deprint/build-tools-cpp) package, v2.0.2

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34

Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
  at Projects.module.exports.Projects.onFileChange (/Users/likask/.atom/packages/build-tools-cpp/lib/projects.coffee:48:16)
  at SettingsView.module.exports.SettingsView.attached (/Users/likask/.atom/packages/build-tools-cpp/lib/settings-view.coffee:132:31)
  at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:481:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:817:14
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -2:17.8.0 window:save-all (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -2:08.8.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:49.6.0 linter:lint (atom-text-editor.editor.vim-mode.command-mode)
  4x -1:28.4.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:23 tree-view:toggle (ul.list-inline.tab-bar.inset-panel)
 11x -1:23 blur (ul.list-inline.tab-bar.inset-panel)
     -0:13 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
     -0:11.5.0 pane:show-next-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
  2x -0:09.3.0 blur (ul.list-inline.tab-bar.inset-panel)
     -0:04.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:02.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 build-tools-cpp:settings (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:01.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "wrap-selection",
      "color-picker",
      "linter-cpplint",
      "set-syntax",
      "red-wavy-underline",
      "linter-clang",
      "minimap-highlight-selected",
      "package-cop",
      "build",
      "trailing-spaces",
      "highlight-selected"
    ],
    "projectHome": "/Users/likask/MyBuild/mofem-cephas/mofem_v0.2"
  },
  "build-tools-cpp": {}
}
```

### Installed Packages

```coffee
# User
build-tools-cpp, v2.0.2
language-cmake, v0.1.4
language-docker, v1.1.3
linter, v0.12.7
minimap, v4.10.0
seti-syntax, v0.4.0
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by deprint** [comment]
Thank you for reporting this issue.
I was only able to replicate this bug when I disabled and enabled my package without reloading the window. It may still be necessary to close and re-open the settings view but executing commands should work fine now.
