### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by cc0code** [deprint/build-tools-cpp#25]
[Enter steps to reproduce below:]

1. I pressed the shortcut for the "first command" which usually compiles my code when suddenly this error occurred.
2. It seems that it has something to do with a new and unsaved "untitled" tab I just created for some quick todo-notes. After closing this tab, everything goes normal again...

**Atom Version**: 1.0.2
**System**: Linux Mint
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v3.0.1

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:983

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:983:15)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
  at Object.module.exports.saveall (/home/user/.atom/packages/build-tools/lib/main.coffee:106:14)
  at Object.module.exports.execute (/home/user/.atom/packages/build-tools/lib/main.coffee:153:6)
  at atom-workspace.subscriptions.add.atom.commands.add.build-tools:first-command (/home/user/.atom/packages/build-tools/lib/main.coffee:55:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -2:35.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:05.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.6.0 build-tools:first-command (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics"
    ]
  },
  "build-tools": {}
}
```

### Installed Packages

```coffee
# User
build-tools, v3.0.1
language-cmake, v0.1.4
linter, v1.2.4
minimap, v4.12.0

# Dev
No dev packages
```

**Comment by cc0code** [comment]
It seems that it has something to do with an new and unsaved "untitled" tab, i just created for some quick todo-notes.

After closing this tab, everything goes normal again...

**Comment by deprint** [comment]
Thanks for reporting the error
