### ISSUE TITLE
Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided dou...

### ISSUE THREAD

**Issue by TheConundrum** [deprint/build-tools-cpp#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.6
**System**: Ubuntu 14.04.3
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v3.2.1

### Stack Trace

Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.

```
At /usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:7117

TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.
  at TypeError (native)
  at jQuery.extend.prop (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:7117:20)
  at jQuery.access (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:3505:5)
  at [object Object].jQuery.fn.extend.prop (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:7081:10)
  at ConsoleOutput.module.exports.ConsoleOutput.setQueueLength (/home/the_engima/.atom/packages/build-tools/lib/console.coffee:145:17)
  at process.BufferedProcess.exit (/home/the_engima/.atom/packages/build-tools/lib/main.coffee:146:24)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:19.4.0 builder:buildfile (atom-text-editor.editor.is-focused)
     -0:10 build-tools:settings (atom-text-editor.editor.is-focused)
     -0:04.0 build-tools:commands (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "build-tools": {}
}
```

### Installed Packages

```coffee
# User
build-tools, v3.2.1
builder, v0.0.1
linter, v1.3.4

# Dev
No dev packages
```

**Comment by deprint** [comment]
Fixed in v3.2.2
