### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by samachr** [deprint/build-tools-cpp#29]
[Enter steps to reproduce below:]

Started happening after upgrade to 1.0 I believe. Might be bad configuration, but something interesting for you all to konw about.

1. try to open settings view from command pallete

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Pro
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v3.4.1

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:116

TypeError: Cannot read property '0' of undefined
  at SettingsView.module.exports.SettingsView.removeSharedPath (C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:116:33)
  at SettingsView.module.exports.SettingsView.updateProjects (C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:95:22)
  at SettingsView.module.exports.SettingsView.reload (C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:142:8)
  at SettingsView.reload (C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:1:1)
  at SettingsView.module.exports.SettingsView.initialize (C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:35:8)
  at SettingsView.View (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new SettingsView (C:\Users\samuelc\.atom\packages\build-tools\lib\settings-view.coffee:10:5)
  at createSettingsView (C:\Users\samuelc\.atom\packages\build-tools\lib\main.coffee:36:22)
  at C:\Users\samuelc\.atom\packages\build-tools\lib\main.coffee:60:9
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\workspace.js:379:19)
  at atom-workspace.subscriptions.add.atom.commands.add.build-tools:settings (C:\Users\samuelc\.atom\packages\build-tools\lib\main.coffee:72:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (C:\Users\samuelc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:36.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:33.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.2.0 build-tools:show (atom-text-editor.editor)
     -0:27.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:24.8.0 build-tools:commands (atom-text-editor.editor)
     -0:21.7.0 grammar-selector:show (atom-text-editor.editor)
     -0:19.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.7.0 fuzzy-finder:toggle-git-status-finder (a.inline-block)
     -0:15.9.0 fuzzy-finder:toggle-buffer-finder (a.inline-block)
     -0:12.9.0 command-palette:toggle (a.inline-block)
     -0:07.4.0 build-tools:commands (a.inline-block)
     -0:06.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:04.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 build-tools:settings (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "vim-mode",
      "minimap-bookmarks",
      "tortoise-svn",
      "welcome",
      "script-runner"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "build-tools": {
    "SaveAll": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
autoclose-html, v0.18.0
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
build-tools, v3.4.1
file-icons, v1.6.6
language-cfml, v0.8.8
minimap, v4.12.3
ruby-block, v0.3.5
script, v2.26.4

# Dev
No dev packages
```

**Comment by deprint** [comment]
I can only reproduce this issue if I open atom without any root folders.
`build-tools` requires at least one open project to function properly (or function at all). Nonetheless it's an uncaught exception so I'll fix it.
