### ISSUE TITLE
ANSI colors support not working

### ISSUE THREAD

**Issue by noirbizarre** [deprint/build-tools-cpp#42]
1. Create a command with Parse ANSI color codes on stderr
2. Run the command

**Atom Version**: 1.1.0
**System**: "Arch Linux"
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v4.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'children' of undefined

```
At /home/noirbizarre/.atom/packages/build-tools/lib/output/ansi-parser.coffee:70

TypeError: Cannot read property 'children' of undefined
  at Object.module.exports.setNextStyle (/home/noirbizarre/.atom/packages/build-tools/lib/output/ansi-parser.coffee:70:25)
  at Object.module.exports.constructElements (/home/noirbizarre/.atom/packages/build-tools/lib/output/ansi-parser.coffee:81:10)
  at Object.module.exports.parseAnsi (/home/noirbizarre/.atom/packages/build-tools/lib/output/ansi-parser.coffee:107:6)
  at Console.module.exports.output.Console.stderr_raw (/home/noirbizarre/.atom/packages/build-tools/lib/output/console.coffee:211:22)
  at /home/noirbizarre/.atom/packages/build-tools/lib/pipeline/output-stream.coffee:48:39
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at OutputStream.module.exports.OutputStream.in (/home/noirbizarre/.atom/packages/build-tools/lib/pipeline/output-stream.coffee:87:24)
  at Socket.<anonymous> (/home/noirbizarre/.atom/packages/build-tools/lib/pipeline/command-worker.coffee:60:13)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -3:15.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:12.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
  2x -3:06.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:59.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:59.6.0 build-tools:first-command (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -1:59.5.0 linter:lint (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -1:16.7.0 pane:show-previous-item (div.build-settings.pane-item)
     -1:15.3.0 build-tools:first-command (atom-text-editor.editor.is-focused)
     -1:14.5.0 linter:lint (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -1:04.4.0 build-tools:first-command (atom-text-editor.editor.is-focused)
     -1:03.7.0 linter:lint (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:14.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
 13x -0:13.1.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:11.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 build-tools:first-command (atom-text-editor.editor.is-focused)
     -0:00.1.0 linter:lint (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules",
      "*.egg-info",
      "*.pyc",
      "*.pyo",
      "__pycache__"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
atom-python-debugger, v0.3.4
atom-ternjs, v0.8.4
autocomplete-python, v0.10.3
build-tools, v4.2.0
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
hidpi, v0.7.0
language-ansible, v0.1.3
language-ini, v1.14.0
language-nginx, v0.6.1
language-restructuredtext, v0.9.0
language-vue, v0.4.0
linter, v1.10.0
linter-flake8, v1.9.1
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-less, v2.2.0
linter-shellcheck, v1.0.2
linter-xmllint, v0.0.7
pigments, v0.18.1
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by deprint** [comment]
Simple typo :smile: 
stderr should work now.

**Comment by noirbizarre** [comment]
Wow, that was fast ! Thanks !!!
