### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Thoma\Documents\AR_OpenCV\.build-t...

### ISSUE THREAD

**Issue by day360** [deprint/build-tools-cpp#44]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v4.2.3

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Thoma\Documents\AR_OpenCV\.build-tools.cson'

```
At fs.js:97

Error: EPERM: operation not permitted, open 'C:\Users\Thoma\Documents\AR_OpenCV\.build-tools.cson'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (C:\Users\Thoma\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
  at Object.module.exports.writeFileSync (C:\Users\Thoma\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\season\lib\cson.js:224:17)
  at ProjectConfig.module.exports.ProjectConfig.save (C:\Users\Thoma\.atom\packages\build-tools\lib\provider\project.coffee:167:12)
  at BuildToolsProject._save (C:\Users\Thoma\.atom\packages\build-tools\lib\provider\project.coffee:1:1)
  at BuildToolsProject.module.exports.model.BuildToolsProject.save (C:\Users\Thoma\.atom\packages\build-tools\lib\provider\build-tools.coffee:50:10)
  at C:\Users\Thoma\.atom\packages\build-tools\lib\provider\build-tools.coffee:142:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Thoma\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at BuildToolsProject.module.exports.model.BuildToolsProject.replaceCommand (C:\Users\Thoma\.atom\packages\build-tools\lib\provider\build-tools.coffee:97:20)
  at CommandPane.success_callback (C:\Users\Thoma\.atom\packages\build-tools\lib\provider\build-tools.coffee:186:24)
  at CommandPane.module.exports.CommandPane.accept (C:\Users\Thoma\.atom\packages\build-tools\lib\view\command-edit-pane.coffee:184:8)
  at HTMLDivElement.<anonymous> (C:\Users\Thoma\.atom\packages\build-tools\lib\view\command-edit-pane.coffee:1:1)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Thoma\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\Thoma\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "build-tools": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.8.0
build-tools, v4.2.3
file-icons, v1.6.11
language-latex, v0.6.1
latex, v0.28.2
pdf-view, v0.34.0
Remote-FTP, v0.7.10

# Dev
No dev packages
```

**Comment by deprint** [comment]
A little more information would be appreciated, so far I can't spot a mistake in the package.

**Comment by day360** [comment]
The file was created on OSX and the error came up on windows. Both using
same version of Atom and your build-tools package.

Apart from that I don't know what I could provide you that would help

**Comment by deprint** [comment]
Can you open/edit `.build-tools.cson` with other editors ?
Can you create a new `.build-tools.cson` in windows (after making a backup of the old one, if necessary) ?
Maybe its really "just" a permission problem. I never used OSX or Windows, so I'm out of ideas.

**Comment by day360** [comment]
I am able to open .build-tools.cson in sublime text and edit it without
error and i am able to create a new version and edit that aswell

**Comment by deprint** [comment]
Well, if you can create and use a new `.build-tools.cson` then I guess it really was a permission problem, not a bug in my package. If you encounter this problem again, it would be nice if you could also include the `.build-tools.cson` in question. So far I don't know of anything that could cause this error.
