### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setIcon' of null

### ISSUE THREAD

**Issue by pawel-jakubowski** [deprint/build-tools-cpp#66]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 15.10
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v4.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setIcon' of null

```
At /home/pjakubow/.atom/packages/build-tools/lib/console/tab.coffee:49

TypeError: Cannot read property 'setIcon' of null
    at Tab.module.exports.Tab.setFinished (/home/pjakubow/.atom/packages/build-tools/lib/console/tab.coffee:49:16)
    at Console.module.exports.output.Console.exitCommand (/home/pjakubow/.atom/packages/build-tools/lib/output/console.coffee:263:14)
    at OutputInterface.module.exports.OutputInterface.finish (/home/pjakubow/.atom/packages/build-tools/lib/pipeline/output-interface.coffee:36:16)
    at OutputManager.module.exports.OutputManager.finish (/home/pjakubow/.atom/packages/build-tools/lib/pipeline/io-manager.coffee:29:18)
    at ChildProcess.<anonymous> (/home/pjakubow/.atom/packages/build-tools/lib/environment/child-process.coffee:119:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -3:29 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:29 build-tools:commands (div.build-settings.pane-item)
  2x -3:23.8.0 core:close (div.build-settings.pane-item)
     -3:20.1.0 build-tools:commands (atom-text-editor.editor.is-focused)
     -3:18.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:17.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:17.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:37.5.0 build-tools:commands (atom-text-editor.editor.is-focused)
     -1:35.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:02.0 build-tools:commands (atom-text-editor.editor.is-focused)
     -1:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:58 linter:lint (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:21.8.0 build-tools:commands (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 build-tools:commands (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "selection-highlight"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Zen, v0.16.4
atom-beautify, v0.29.6
autocomplete-python, v1.7.2
build-tools, v4.5.0
build-tools-make, v0.2.1
eclipse-keybindings, v0.9.0
language-cmake, v0.1.4
language-cpp14, v0.6.1
language-dot, v1.6.0
language-latex, v0.6.1
language-plantuml, v0.2.0
language-prolog, v0.10.0
latex, v0.32.0
linter, v1.11.4
linter-chktex, v1.3.0
pdf-view, v0.50.0
project-viewer, v0.2.32
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by deprint** [comment]
I assume this happened when you closed a console tab while the process was still running ?

**Comment by pawel-jakubowski** [comment]
No, it happened when I had only linter output setted. I compiled latex document and no linter messages showed up (I assume it does not support latex compiler output)

**Comment by deprint** [comment]
I added a few checks to make sure that the error does not happen, but this fix does not deal with the source of the problem. If (as you say) only linter output is enabled then the console pane shouldn't even be active (let alone throw errors).

About linter messages: No, this package does not support latex compiler output. However, it can be configured to highlight these errors. I never used latex and don't know how latex compiler errors look like.
