### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by dexif** [deprint/build-tools-cpp#70]
[Enter steps to reproduce below:]

1. create .build-tools.cson
2. Accept

**Atom Version**: 1.12.0-beta5
**Electron Version**: 1.3.6
**System**: Ubuntu 16.04.1
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v4.5.3

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of null

```
At /home/.../.atom/packages/build-tools/lib/view/command-edit-highlighting-pane.coffee:86

TypeError: Cannot read property 'get' of null
    at HighlightingPane.module.exports.HighlightingPane.get (/home/.../.atom/packages/build-tools/lib/view/command-edit-highlighting-pane.coffee:86:15)
    at CommandPane.module.exports.CommandPane.accept (/home/.../.atom/packages/build-tools/lib/view/command-edit-pane.coffee:185:14)
    at HTMLDivElement.<anonymous> (/home/.../.atom/packages/build-tools/lib/view/command-edit-pane.coffee:1:1)
    at space-pen-div.dispatch (/home/.../.atom/packages/build-tools/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/home/.../.atom/packages/build-tools/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -4:10.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:06.7.0 build-tools:commands (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:05.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:05.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:03.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-compact.seti-icons.seti-roboto.seti-animate.theme-one-dark-syntax.theme-seti-ui)
     -4:00.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:00.4.0 build-tools:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-compact.seti-icons.seti-roboto.seti-animate.theme-one-dark-syntax.theme-seti-ui)
     -3:05.2.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:55.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:55.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-compact.seti-icons.seti-roboto.seti-animate.theme-one-dark-syntax.theme-seti-ui)
     -2:35.3.0 build-tools:add-Custom-Commands (span#add-provider.inline-block.btn.btn-sm.icon.icon-plus)
     -1:00.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:59.8.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -0:58.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -0:56.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php",
      "autocomplete-php",
      "grunt-runner",
      "linter-php",
      "term3",
      "terminal-plus",
      "project-manager",
      "scroll-searcher",
      "hyperclick",
      "hyperclick-php",
      "js-hyperclick"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules",
      "bower_components"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.19.4 (inactive)
atom-beautify, v0.29.13 (active)
atom-formatter-jsbeautify, v1.1.2 (active)
atom-html-preview, v0.1.22 (active)
auto-indent-file, v0.2.0 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-json, v5.1.0 (active)
autocomplete-php, v0.3.7 (inactive)
autocomplete-plus, v2.33.1 (active)
build-tools, v4.5.3 (active)
cssfmt, v1.4.0 (inactive)
editor-stats, v0.17.0 (active)
editorconfig, v1.7.0 (active)
emmet, v2.4.3 (active)
foldername-tabs, v0.2.3 (active)
font-viewer, v0.3.1 (active)
git-blame, v0.4.11 (inactive)
git-control, v0.8.2 (inactive)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.18.0 (active)
git-projects, v1.17.0 (inactive)
git-status, v0.3.4 (inactive)
git-time-machine, v1.5.3 (inactive)
goto-definition, v1.1.19 (active)
grunt-runner, v0.14.0 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.39 (inactive)
hyperclick-php, v0.2.1 (inactive)
js-hyperclick, v1.9.0 (inactive)
jshint, v1.8.6 (active)
language-nginx, v0.6.2 (active)
linter, v1.11.18 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.3.1 (inactive)
minimap, v4.25.6 (active)
minimap-autohide, v0.10.1 (active)
minimap-git-diff, v4.3.1 (active)
navigate, v0.1.16 (active)
package-cop, v0.2.10 (active)
pretty-json, v1.6.1 (active)
project-manager, v3.3.3 (inactive)
project-viewer, v0.3.25 (active)
react, v0.16.1 (active)
rest-client, v1.3.1 (active)
scroll-searcher, v5.0.0 (inactive)
scroll-sync, v0.1.5 (inactive)
seti-icons, v1.3.4 (active)
seti-ui, v1.3.2 (active)
symbols-tree-view, v0.13.2 (active)
sync-settings, v0.7.2 (active)
synced-sidebar, v0.4.3 (active)
term, v0.2.4 (inactive)
term3, v0.22.1 (inactive)
terminal-plus, v0.14.5 (inactive)
todo, v0.6.0 (inactive)
trailing-spaces, v0.3.2 (active)
tree-view-git-branch, v0.1.2 (active)
tree-view-git-status, v1.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.102.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by deprint** [comment]
Thanks for the report.

`v4.5.4` fixes a few issues I had wih Atom's beta channel, maybe it also fixes your problem.

Unfortunately I was not able to reproduce your bug. You said you created a `.build-tools.cson` and clicked on the "Accept"-Button of the command editor(?). If the issue persists, it would be nice if you could you tell me what happened between creating the file and clicking that button.
