### ISSUE TITLE
Uncaught ReferenceError: exitQueue is not defined

### ISSUE THREAD

**Issue by xHasKx** [deprint/build-tools-cpp#74]
1. use simple Makefile project (C++)
2. make some C++ error
3. run build

**Atom Version**: 1.13.0-beta8
**Electron Version**: 1.3.13
**System**: Linux Mint
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package, v4.5.6

### Stack Trace

Uncaught ReferenceError: exitQueue is not defined

```
At /home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/output/linter.coffee:92

ReferenceError: exitQueue is not defined
    at Linter.module.exports.output.Linter.stderr_linter (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/output/linter.coffee:92:9)
    at /home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-pipeline.coffee:31:39
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at OutputPipeline.module.exports.OutputPipeline.pushLinterMessage (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-pipeline.coffee:98:20)
    at OutputPipeline.pushLinterMessage (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-pipeline.coffee:1:1)
    at OutputPipeline.module.exports.OutputPipeline.lint (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-pipeline.coffee:125:10)
    at OutputPipeline.lint (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-pipeline.coffee:1:1)
    at GCCClang.module.exports.GCCClang.in (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/profiles/gcc_clang.coffee:58:17)
    at ProfileModifier.module.exports.modifier.ProfileModifier.modify1 (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/stream-modifiers/profile.coffee:79:9)
    at OutputPipeline.module.exports.OutputPipeline.in (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-pipeline.coffee:60:23)
    at OutputStream.module.exports.OutputStream.in (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/pipeline/output-stream.coffee:54:13)
    at Socket.<anonymous> (/home/hask/data/nextCloud/mirror/.atom/packages/build-tools/lib/environment/child-process.coffee:128:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -0:01.7.0 build-tools:commands (input.hidden-input)
     -0:00.3.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-control",
      "symbols-view",
      "gdb-debug",
      "git-diff-details",
      "git-history",
      "git-log",
      "git-plus",
      "spell-check",
      "goto-last-edit",
      "build",
      "build-make"
    ],
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v5.0.0 (active)
atom-format-lua, v0.1.5 (inactive)
atom-sync, v0.7.3 (active)
atom-terminal, v0.8.0 (inactive)
autocomplete-ctags, v0.4.1 (active)
autocomplete-lua, v0.8.0 (active)
build, v0.67.0 (inactive)
build-make, v0.13.0 (inactive)
build-tools, v4.5.6 (active)
busy, v0.7.0 (active)
cursor-history, v0.9.1 (active)
dbg, v1.3.1 (active)
dbg-gdb, v1.4.0 (active)
gdb-debug, v0.0.3 (inactive)
git-control, v0.8.2 (inactive)
git-diff-details, v1.4.0 (inactive)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (inactive)
git-plus, v7.0.4 (inactive)
goto-last-edit, v0.3.2 (inactive)
highlight-selected, v0.11.2 (active)
language-lua, v0.9.11 (active)
language-tcl, v0.1.2 (active)
linter, v1.11.21 (active)
linter-lua, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
output-panel, v0.1.4 (active)
split-diff, v1.1.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by deprint** [comment]
Thanks for the report!
