### ISSUE TITLE
Uncaught TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by sourav-dey** [deprint/build-tools-cpp#76]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package 4.5.7

### Stack Trace

Uncaught TypeError: Cannot read property 'key' of undefined

```
At C:\Users\sourav.dey\.atom\packages\build-tools\lib\view\command-edit-stream-pane.coffee:107

TypeError: Cannot read property 'key' of undefined
    at /packages/build-tools/lib/view/command-edit-stream-pane.coffee:107:18)
    at /packages/build-tools/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/build-tools/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -8:28.7.0 core:move-down (input.hidden-input)
     -8:28.4.0 autocomplete-plus:confirm (input.hidden-input)
  4x -8:25.8.0 core:backspace (input.hidden-input)
  2x -8:22.6.0 autocomplete-plus:confirm (input.hidden-input)
     -8:13.5.0 core:move-right (input.hidden-input)
  2x -8:09.7.0 core:move-left (input.hidden-input)
  5x -8:09.1.0 core:backspace (input.hidden-input)
     -6:31.5.0 core:confirm (input.hidden-input)
     -4:54.1.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:29 core:confirm (input.hidden-input)
  2x -4:17.8.0 build-tools:add-Custom-Commands (span#add-provider.inline-block.btn.btn-sm.icon.icon-plus)
 12x -3:11.5.0 core:backspace (input.hidden-input)
     -0:23 build-tools:add-all (span#add-modifier.inline-block.btn.btn-sm.icon.icon-plus)
```

### Non-Core Packages

```
autocomplete-clang 0.10.0 
build-cmake 0.9.1 
build-tools 4.5.7 
clang-format 1.28.0 
gpp-compiler 3.0.7 
pretty-json 1.6.1 
xml-formatter 0.10.0 
```

**Comment by deprint** [comment]
Thanks for the report
