### ISSUE TITLE
Failed to activate the build-tools package

### ISSUE THREAD

**Issue by Nowass** [deprint/build-tools-cpp#77]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta0 x64
**Electron**: 1.3.14
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [build-tools](https://github.com/deprint/build-tools-cpp) package 4.5.8

### Stack Trace

Failed to activate the build-tools package

```
At this.element.getModel is not a function

TypeError: this.element.getModel is not a function
    at /packages/asciidoc-image-helper/node_modules/atom-space-pen-views/lib/text-editor-view.js:40:34)
    at Object.content (/packages/build-tools/lib/console/console-element.coffee:17:35)
    at Builder.tag (/packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/build-tools/lib/console/console-element.coffee:16:12)
    at Builder.tag (/packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/build-tools/lib/console/console-element.coffee:11:10)
    at Builder.tag (/packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.ConsoleView.content (/packages/build-tools/lib/console/console-element.coffee:6:8)
    at /packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/asciidoc-image-helper/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/build-tools/lib/console/console-element.coffee:5:5)
    at Object.activate (/packages/build-tools/lib/output/console.coffee:35:23)
    at Object.activate (/packages/build-tools/lib/output/output.coffee:45:9)
    at Object.provideConsole (/packages/build-tools/lib/main.coffee:76:50)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package.js:443:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package.js:256:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/package-manager.js:600:1)
    at ~/AppData/Local/atom/app-1.17.0-beta0/resources/app/src/atom-environment.js:831:1
```

### Commands

```
```

### Non-Core Packages

```
apidoc-snippets 0.1.1 
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.0 
atom-alignment 0.12.1 
atom-beautify 0.29.18 
atom-material-numix-syntax 0.2.1 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-terminal-panel 4.4.4 
autocomplete-asciidoc 0.1.2 
build 0.67.0 
build-make 0.13.0 
build-tools 4.5.8 
busy 0.7.0 
busy-signal 1.3.0 
file-templates 0.2.0 
file-type-icons 1.3.3 
intentions 1.1.2 
language-asciidoc 1.10.0 
linter 2.1.2 
linter-cppcheck 0.2.3 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
nav-panel 0.0.11 
one-dark-material-syntax 1.0.3 
pandoc-convert 1.1.0 
pdf-view 0.57.0 
project-manager 3.3.4 
todo-show 1.11.0 
```

**Comment by deprint** [comment]
I can replicate the bug in atom v1.17.0-beta0, but not in v1.16.0. I think this is a problem in Atom, not my package.
I'll try to figure out what's going on here.

**Comment by deprint** [comment]
Someone already brought it up in atom/atom#14193

**Comment by deprint** [comment]
v1.17.0-beta1 fixes it, so I'll close this.
